= Implementing Microservices with MicroProfile Hands-on-Lab

== Content
In this workshop you will learn about the MicroProfile programming model for developing microservice applications. 
Although MicroProfile is currently based on Java EE technologies, the expectation is that this will evolve to using the corresponding Jakarta EE technologies.

We will go through the APIs and implementations for:

* Externalized Configuration
* Fault Tolerance
* Health Checks
* Application Metrics
* Security
* Open API
* Open Tracing
* Client API

You will learn how to run you applications in available implementations from different vendors.

== Structure
The is structured as a practical workshop where you work with practical exercises alone or in pairs. 
Each section of exercises will introduced with a short lecture on the topic and followed by a walk-through of the solution.

== Prerequisites
Participants must have good knowledge of the Java programming language and general knowledge of servers side programming. 
Experience in Java EE knowledge is an advantage, but not required.

=== Required Software
* JDK
* Maven
* IDE (link:https://www.eclipse.org/downloads/[Eclipse IDE],
link:https://netbeans.apache.org/download/nb110/nb110.html[Apache NetBeans],
link:https://www.jetbrains.com/idea/download/#section=mac[IntelliJ IDEA])
* Git

= Exercises
 * link:part-1/README.adoc[Part 1]
 * link:part-2/README.adoc[Part 2]
 * link:part-3/README.adoc[Part 3]
 * link:solution/README.adoc[Solution] +
   (Don't look before you have completed the workshop, or at least had a try at it...)
