= Part 3

In this part, you will learn about communicating between services.

== Objective

Learn

== Instructions

=== Preparations

==== Capitalize Service

. Navigate to link:https://start.microprofile.io/[start.microprofile.io]
. Fill in the form with: 
 - GroupId: dukes 
 - ArtifactId: capitalize 
 - MicroProfile Version: MP 3.3
 - MicroProfile Serer: Payara Micro
 - Examples for specifications: Deselect all (we will look at them later)
. Click *DOWNLOAD*
. Unzip _capitalize.zip_
. Build capitalize: `mvn clean package`
. Run capitalize: `java -jar target/capitalize-microbundle.jar`

==== Birthday Service

. Install link:https://helidon.io/docs/latest/#/about/05_cli[Helidon CLI]
. *helidon init*
 - *2* (MP)
 - *1* (bare)
 - Project Name: *birthday*
 - Project GroupId: *dukes*
 - Project ArtifactId: *birthday*
 - Project Version: *1.0-SNAPSHOT*
 - Java package name: *dukes.birthday*
 - Start developmen loop: *n*
 - Rename project folder: `mv bare-mp birthday`

Build and start the service:

```bash
cd birthday
helidon dev
```
 
Create a CDI Bean that can calculate the days until and since a birthday (given a birthday) and the age of the person?

```java
@RequestScoped
public class BirthDayService {

    private final LocalDate now = now();

    public long calculateDaysToBirthday(LocalDate bd) {

        final LocalDate bdThisYear = bd.withYear(now.getYear());

        if (bdThisYear.isAfter(now)) {
            return now.until(bdThisYear, DAYS);
        } else {
            return now.until(bdThisYear.plusYears(1), DAYS);
        }
    }

    public long calculateDaysSinceBirthday(LocalDate bd) {

        final LocalDate bdThisYear = bd.withYear(now.getYear());

        if (bdThisYear.isBefore(now)) {
            return bdThisYear.until(now, DAYS);
        } else {
            return bdThisYear.minusYears(1).until(now, DAYS);
        }
    }

    public long age(LocalDate bd) {
        return bd.until(now, YEARS);
    }
}
```

Next, expose a REST service that allows you can call the above as services.

==== Capitalize Service

Create a new REST Endpoint in the capitalize service that can take in a word and capitalize it:

```java
@Path("/capitalize")
@ApplicationScoped
public class CapitalizeController {

    @GET
    @Path("/{word}")
    public String capitalize(@PathParam("word") String word) {
        return word.substring(0, 1).toUpperCase() + word.substring(1).toLowerCase();
    }
}
```

Build and start the service:

```bash
mvn clean package
java -jar target/capitalize-microbundle.jar --port 8070
```

=== REST Client

From the greeting service, make a call to the birthday service, that in turn should call the capitalize service to capitalize the name, and then return birthday information.

Use MicroProfile REST client to make these client calls. Here is an example of what you need to call the capitalize service:

```java
@Path("capitalize")
@Dependent
@RegisterRestClient
public interface CapitalizeService {

    @GET
    @Path("{word}")
    String capitalize(@PathParam("word") String word);
}
```

*TIP:* Remember to configure the REST client. Here is an example for the client to the capitalize service.

birthday/src/main/resources/META-INF/microprofile-config.properties

```
dukes.birthday.CapitalizeService/mp-rest/url=http://localhost:8070
```

=== Fault Tolerance

Now let's stop the `capitalization` service. Hit the `hello service` again. You will see an ugly exception.

Fix this by adding a `@Fallback` to the Rest client proxy that calls that service.

Next let's add a way to `@Retry` the birthday service (from hello service) when birthday is not available.

Retry that service 30 time with a 1 second delay.

When the server does not come back up in time, do a `@Fallback`.

=== Security (optional)

Add security to the `greeting` service. Only allow users with the role `protected` to be able to access the endpoint.

==== Configuration

Add the public key to the Liberty configuration.

Copy link:https://github.com/ivargrimstad/microprofile-hol/raw/master/solution/greeting/src/main/liberty/config/resources/security/public.jks[public.jks] to the `src/main/liberty/config/resources/security` folder of the `greeting` service (you may need to create the folder structure).


== Resources

- link:https://microprofile.io/project/eclipse/microprofile-fault-tolerance[MiroProfile Fault Tolerance]
- link:https://microprofile.io/project/eclipse/microprofile-jwt-auth[MicroProfile JWT RBAC]