= Part 3

In this part, you will learn about communicating between services.

== Objective

Learn

== Instructions

=== Preparations

. Navigate to link:https://start.microprofile.io/[start.microprofile.io]
. Fill in the form with: 
 - GroupId: dukes 
 - ArtifactId: birthday 
 - MicroProfile Version: MP 2.2
 - MicroProfile Serer: Thorntail V2
 - Examples for specifications: Deselect all (we will look at them later)
. Click *DOWNLOAD*
. Unzip _birthday.zip_
. Build birthday: *mvn clean package*
. Run birthday: *java -jar target/birthday-thorntail.jar*

. Navigate to link:https://start.microprofile.io/[start.microprofile.io]
. Fill in the form with: 
 - GroupId: dukes 
 - ArtifactId: capitalize 
 - MicroProfile Version: MP 2.2
 - MicroProfile Serer: Payara Micro
 - Examples for specifications: Deselect all (we will look at them later)
. Click *DOWNLOAD*
. Unzip _capitalize.zip_
. Build capitalize: *mvn clean package*
. Run capitalize: *java -jar target/birthday-thorntail.jar*

=== Zipkin

(If you have docker installed)

Start a Zipkin server to collect traces

You can browse to the zipkin server UI here :

link:http://localhost:9411/[http://localhost:9411/]

```bash
docker run -d -p 9411:9411 openzipkin/zipkin
```

=== REST services

==== Birthday Service

Create a CDI Bean that can calculate the days until and since a birthday (given a birthday) and the age of the person?

```java
@RequestScoped
public class BirthDayService {

    private final LocalDate now = now();

    public long calculateDaysToBirthday(LocalDate bd) {

        final LocalDate bdThisYear = bd.withYear(now.getYear());

        if (bdThisYear.isAfter(now)) {
            return now.until(bdThisYear, DAYS);
        } else {
            return now.until(bdThisYear.plusYears(1), DAYS);
        }
    }

    public long calculateDaysSinceBirthday(LocalDate bd) {

        final LocalDate bdThisYear = bd.withYear(now.getYear());

        if (bdThisYear.isBefore(now)) {
            return bdThisYear.until(now, DAYS);
        } else {
            return bdThisYear.minusYears(1).until(now, DAYS);
        }
    }

    public long age(LocalDate bd) {
        return bd.until(now, YEARS);
    }
}
```

Next, expose a REST service that allows you can call the above as services.

Build and start the service (Note the port input):

```bash
mvn clean package
java -jar target/birthday-thorntail.jar 
```

==== Capitalize Service

Create a new REST Endpoint in the capitalize service that can take in a word and capitalize it:

```java
@Path("/capitalize")
@ApplicationScoped
public class CapitalizeController {

    @GET
    @Path("/{word}")
    public String capitalize(@PathParam("word") String word) {
        return word.substring(0, 1).toUpperCase() + word.substring(1);
    }
}
```

Build and start the service:

```bash
mvn clean package
java -jar target/capitalize-microbundle.jar
```

=== REST Client

From the name service, make a call to the birthday service, that in turn should call the capitalize service to capitalize the name, 
and then return birthday information.

Use MicroProfile REST client to make these client calls. Here is an example of what you need to call the capitalize service:

```java
@Path("capitalize")
@Dependent
@RegisterRestClient
public interface CapitalizeService {

    @GET
    @Path("{word}")
    String capitalize(@PathParam("word") String word);
}
```

=== Distributed Tracing

Add tracing to your services in order to be able to trace calls across services.

You may use both the `@Traced` annotation and the programmatic `Tracer`.

=== Fault Tolerance

Now let's stop the `capitalization` service. Hit the `hello service` again. You will see an ugly exception.

Fix this by adding a `@Fallback` to the Rest client proxy that calls that service.

=== Security (optional)

